/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { KnowledgeGraphTypeDto } from './knowledgeGraphTypeDto';
import type { RelationDto } from './relationDto';

export interface KnowledgeGraphDto {
  graphName?: string;
  graphUri?: string;
  knowledgeGraphType?: KnowledgeGraphTypeDto;
  relations?: RelationDto[];
  contains?: KnowledgeGraphDto[];
}
