/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface NewKnowledgeGraphDto {
  userId?: string;
  graphUri?: string;
  graphName?: string;
  graphTypeUri?: string;
  isDefault?: boolean;
}
