/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { RelationTypeDto } from './relationTypeDto';

export interface RelationDto {
  relationType?: RelationTypeDto;
  relationUri?: string;
  from?: string;
  to?: string;
}
