/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { UserGraphDto } from './userGraphDto';

export interface UserDto {
  userId?: string;
  displayName?: string;
  friends?: UserDto[];
  userGraph?: UserGraphDto;
}
